name: Check CI

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Run CI
        run: yarn ci
